FROM python:3.11-slim-buster

ENV APP_HOME=/srv/mvp_crm/backend

RUN apt-get update \
    && apt-get install -y --no-install-recommends netcat \
    && pip install --upgrade pip \
    && mkdir -p $APP_HOME

WORKDIR $APP_HOME

COPY ./setup.py ./
RUN pip install -e ./

COPY . $APP_HOME

RUN chmod +x $APP_HOME/start.sh


COPY . $APP_HOME
RUN  python manage.py makemigrations
RUN  python manage.py migrate
RUN  python manage.py download_data
RUN python manage.py collectstatic
RUN "from users.models import User; \
      User.objects.filter(email='$EMAIL').delete(); \
      User.objects.create_superuser('$LOGIN', '$EMAIL', '$PASSWORD')" \
      | python manage.py shell \
      && echo "Superuser created"
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mvp_crm.wsgi"]
#ENTRYPOINT ["./start.sh"]
