FROM python:3.11-slim-buster

ENV APP_HOME=/srv/mvp_crm/backend

RUN apt-get update \
    && apt-get install -y --no-install-recommends netcat \
    && pip install --upgrade pip \
    && mkdir -p $APP_HOME

WORKDIR $APP_HOME

COPY ./setup.py ./
RUN pip install -e ./

COPY ./start.sh ./

COPY . $APP_HOME
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "mvp_crm.wsgi"]
#ENTRYPOINT ["./start.sh"]